# beta_users expects a CSV list of email addresses
beta_users: <%= ENV['BETA_USERS_LIST'] || '' %>

google_api:
  client_id: <%= ENV['GOOGLE_API_CLIENT_ID'] || '' %>
  client_secret: <%= ENV['GOOGLE_API__CLIENT_SECRET'] || '' %>

twilio_api:
  account_sid: <%= ENV['TWILIO_API_ACCOUNT_SID'] || '' %>
  auth_token: <%= ENV['TWILIO_API_AUTH_TOKEN'] || '' %>
  phone_number: <%= ENV['TWILIO_API_PHONE_NUMBER'] || '' %>
